name: Release on GitHub

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'gradle'
    - name: Prepare Android keystore
      run: echo ${{ secrets.ENCODEDKEYSTORE }} | base64 --decode > app/keystore.jks
    - name: Download dependencies
      run: ./gradlew androidDependencies
    - name: Build release APK
      run: ./gradlew assembleRelease
      env:
        APPID: de.szalkowski.activitylauncher.oss
        KEYSTORE: keystore.jks
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTOREPASSWORD }}
        KEY_ALIAS: de.szalkowski.activitylauncher.oss
        KEY_PASSWORD: ${{ secrets.KEYPASSWORD }}
    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.ref }}
        tag_name: ${{ github.ref }}
        body_path: whatsnew/whatsnew-en-GB
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Upload Release APK
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app/build/outputs/apk/release/app-release.apk
        asset_name: ActivityLauncher-${{ github.ref }}.apk
        asset_content_type: application/vnd.android.package-archive
      env:
        GITHUB_TOKEN: ${{ github.token }}
