name: Update Play Store listing

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: 

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: 
      - name: haha
        run: python3 update-listing.py
        env:
          SERVICEACCOUNT: ${{ sERVICEACCOUNT }}
          SERVICEACCOUNT_EMAIL: ${{.SOUNT_EMAIL }}
